apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timetable-manager
  template:
    metadata:
      labels:
        app: timetable-manager
    spec:
      containers:
        - name: timetable-manager
          imagePullPolicy: Never
          image: timetable_manager:latest
          ports:
            - containerPort: 8000
