apiVersion: v1
kind: Service
metadata:
  name: timetable-manager-service
spec:
  type: NodePort
  selector:
    app: timetable-manager
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
