apiVersion: v1
kind: Service
metadata:
  name: timetable_manager-service
spec:
  type: NodePort
  selector:
    app: timetable_manager
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
